### ISSUE TITLE
NTPDATE binary missing

### ISSUE THREAD

**Issue by flyddw** [deweysasser/docker-xymon#6]
ntpdate binary is missing from the container. when installed manually, it works ok.

**Comment by zethis** [comment]
In my case, tzdata fix the problem:
without tzdata: 
docker run -it -e TZ=Europe/Paris xymon:test bash
root@8cd48e710fd8:/# date
Sat Jul  4 07:34:47 Europe 2020

with tzdata:

docker run -it --rm -e TZ=Europe/Paris xymon:test bash 
root@96e8ede16a52:/# date
Sat Jul  4 09:46:12 CEST 2020
